version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: muffin-postgres
    environment:
      POSTGRES_DB: muffin_wallet
      POSTGRES_USER: muffin-wallet
      POSTGRES_PASSWORD: muffin-wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U muffin-wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
