namespace:
  create: true
  name: muffin-services

gateway:
  enabled: true
  host: wallet.example.com

virtualServices:
  wallet:
    enabled: true
  currency:
    enabled: true

serviceEntry:
  postgres:
    enabled: true
    host: host.minikube.internal
    port: 5432
    address: ""
    resolution: DNS

peerAuthentication:
  enabled: true
  mode: STRICT

authorizationPolicy:
  currency:
    enabled: true

destinationRules:
  wallet:
    enabled: true
  currency:
    enabled: true

prometheus:
  serviceMonitor:
    enabled: true

thanos:
  enabled: true
  bucket: thanos
  endpoint: host.minikube.internal:9000
  accessKey: minio
  secretKey: minio123
