apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.resource-name" . }}
  labels:
    {{ include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "muffin-wallet.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "muffin-wallet.selector" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.volume }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
          {{- end }}
          {{- if or (.Values.envFrom.secrets) (.Values.envFrom.configMaps) }}
          envFrom:
            {{- range .Values.envFrom.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.envFrom.configMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      {{- if .Values.volume }}
      volumes:
        - name: {{ .Values.volume.name }}
          configMap:
            name: {{ .Values.volume.configMapName }}
      {{- end }}
