apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.resource-name" . }}
  labels:
    {{ include "muffin-wallet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "muffin-wallet.selector" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
