meshConfig:
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  defaultConfig:
    proxyStatsMatcher:
      inclusionRegexps:
        - ".*circuit_breakers.*"
        - ".*upstream_rq_retry.*"
        - ".*upstream_rq_timeout.*"
      inclusionPrefixes:
        - "cluster_manager"
        - "listener_manager"
        - "server"
        - "cluster.xds-grpc"
    tracing:
      sampling: 100.0
      zipkin:
        address: jaeger.istio-system.svc.cluster.local:9411

pilot:
  traceSampling: 100.0
  env:
    PILOT_ENABLE_WORKLOAD_ENTRY_CROSS_CLUSTER: "false"
