auth:
  strategy: anonymous

deployment:
  ingress:
    enabled: false

server:
  web_root: /
  port: 20001

external_services:
  prometheus:
    url: http://prometheus-operated:9090
  grafana:
    enabled: false
  tracing:
    enabled: true
    in_cluster_url: http://jaeger.istio-system:16686
    use_grpc: false
